development:
  adapter: postgresql
  database: Production
  username: postgres
  password: Abixel2096
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: Test
  username: postgres
  password: Abixel2096
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: Production
  username: postgres
  password: Abixel2096
  host: localhost
  pool: 5
  timeout: 5000
