# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 369239cb0b545c3e90c63127acdeb543bcf2facdc4faef4f06fbc4c71ad60a547a7555463b100559716488c37648adad5610e230abf56897f1edf300cbfe7f99

test:
  secret_key_base: 352525863e66c22e5231b05edb9ffdb5cbba4c6ad440be79e55318c0bd06fe23f716eb0da0d71ee42a682c20ef1e00a95272b406b0849410298e1b7c95e886c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
